### ISSUE TITLE
No scan topic being published.

### ISSUE THREAD

**Issue by rs1990** [ros-drivers/urg_node#14]
I am trying to get the Hokuyo  UTM-30LX-EW  working with my robot but when ever i try to run the lidar, i dont see any scan topic being published. I have /echoes /first /last /urg/update parameters and others being published but no /scan. 

Any help ??

**Comment by chadrockey** [comment]
It's defaulting to multi-echo mode.  You should be able to use /first or /last as you would /scan.

If you want to revert to the internal single echo mode, set the parameter publish_multiecho to false:
https://github.com/ros-drivers/urg_node/blob/indigo-devel/src/urg_node.cpp#L213
