### ISSUE TITLE
Problems with Hokuyo 04LX

### ISSUE THREAD

**Issue by davide-tateo90** [ros-drivers/urg_node#23]
Hi,
I'm trying to use the URG-04LX sensor, with the new urg_node. When I try to connect I get:
[ERROR] [1481563459.541562213]: Unknown error connecting to Hokuyo

While, if I'm using the old hokuyo_node, the sensor just work correctly.
Also, if I try to connect using the urg_node after killing the hokuyo node, the new node works.

 I've tried with different parameters and disabling/enabling calibration

Also I've updated the sensor to the latest version (Ver3.4.03) without success.

Restarting the sensor doesn't work, as it enters in a loop of error states.

rosrun urg_node urg_node 
[ INFO] [1481562698.401506634]: Connected to serial device with ID: receive error.
[ INFO] [1481562698.528700165]: Streaming data.
[ WARN] [1481562700.164722195]: Could not grab single echo scan.
[ERROR] [1481562706.575695889]: Error count exceeded limit, reconnecting.
[ INFO] [1481562710.064727728]: Connected to serial device with ID: receive error.
[ERROR] [1481562710.165523797]: Tried to advertise a service that is already advertised in this node [/urg_node/set_parameters]
[ INFO] [1481562710.187120186]: Streaming data.
[ WARN] [1481562711.828255910]: Could not grab single echo scan.
[ERROR] [1481562718.239361077]: Error count exceeded limit, reconnecting.
[ INFO] [1481562721.728254595]: Connected to serial device with ID: receive error.
[ INFO] [1481562721.849091216]: Streaming data.
[ WARN] [1481562723.491826093]: Could not grab single echo scan.
[ERROR] [1481562729.903079945]: Error count exceeded limit, reconnecting.
[ INFO] [1481562733.392075814]: Connected to serial device with ID: receive error.
[ERROR] [1481562733.492562034]: Tried to advertise a service that is already advertised in this node [/urg_node/set_parameters]
[ INFO] [1481562733.516776507]: Streaming data.
[ WARN] [1481562735.155774107]: Could not grab single echo scan.
[ERROR] [1481562741.566833458]: Error count exceeded limit, reconnecting.

**Comment by davide-tateo90** [comment]
Update: using the verison in the pull request #22 i get a more informative error:

$ rosrun urg_node urg_node 
[ERROR] [1482329968.746021512]: Error connecting to Hokuyo: Could not initialize Hokuyo:
not connected.


$ rosrun urg_node getID /dev/ttyACM0
getID failed: Could not initialize Hokuyo:
not connected.

However the hokuyo is connected and in fact works with the old hokuyo_node:
$ rosrun hokuyo_node hokuyo_node 
[ INFO] [1482330147.593798394]: Connected to device with ID: H0707625
[ INFO] [1482330147.692804670]: Starting calibration. This will take up a few seconds.
[ INFO] [1482330150.783847053]: Calibration finished. Latency is: -0.0810
[ INFO] [1482330151.093119302]: Streaming data.

the hokuyo is on the default serial over usb port:
$ ls /dev/ttyACM*
/dev/ttyACM0

**Comment by bygreencn** [comment]
please check pull-request of https://github.com/ros-drivers/urg_c/pull/4

**Comment by 2scholz** [comment]
I ran into the same problem and found a solution. 
There are two different communication protocols the URG-04LX can use: SCIP1.1 and SCIP2.0. 
The standard default mode for the URG-04LX is SCIP1.1, but the urg_node does not support this mode. 

The solution is to switch to SCIP2.0. 
This can be done by sending a command to the sensor, for example using picocom: 
`sudo picocom /dev/ttyACM0`
Then type `SCIP2.0` and press enter. 

This has to be done at every startup though. 

A more convenient method I haven't tested is to set the default mode to SCIP2.0. 
Details are in this [datasheet](https://en.manu-systems.com/URG_SCIP20.pdf) on page 3.

**Comment by JanezCim** [comment]
I had a similar problem when I was trying it with urg_node installed from binaries. I solved it simply by removing the binaries, and compiling the latest ROS package from urg_node github page https://github.com/ros-drivers/urg_node
