### ISSUE TITLE
urg_node config does not match hokuyo_node config

### ISSUE THREAD

**Issue by t1jump** [ros-drivers/urg_node#4]
I'm having issues using urg_node in place of hokuyo_node with hector_slam. My best guess is differences in config which can be noted by comparing URGConfig.dox to HokuyoConfig.dox. Config can be changed for the hokuyo at Hokuyo.cfg (if I'm remembering correctly) but there is no urg.cfg that I can find. Where can I change config for the urg_node to see if getting the urg set up the same as the hokuyo will resolve issues?

I have posted this on answers.ros but I'm getting no responses.

**Comment by chadrockey** [comment]
Configuration in ROS is not done with one config file per node.  You use
what's called the parameter server:

http://www.ros.org/wiki/Parameter%20Server

The files you are finding (cfgs) are for a very convenient way to change
parameters without restarting the node: dynamic reconfigure.

http://ros.org/wiki/hokuyo_node/Tutorials/UsingReconfigureGUIToChangeHokuyoLaserParameters
