### ISSUE TITLE
What could cause an "Abnormal status" error?

### ISSUE THREAD

**Issue by venkat-ganesh** [ros-drivers/urg_node#43]
Hello,

On Ubuntu 14.04 with ros-indigo, I'm seeing a weird "Abnormal status" error. Here's a screenshot of rqt_robot_monitor -

<img src="https://user-images.githubusercontent.com/32844187/40504818-6408f8e6-5f60-11e8-9b22-71773cdbc080.png" width="300" height="400" title="rqt_error">

Physically, the LIDAR seems to be fine. The LIDAR's LED panel doesn't show any error codes, and I receive data points as expected - 

<img src="https://user-images.githubusercontent.com/32844187/40505055-199e4d1e-5f61-11e8-87c3-480c573ad966.jpg" width="300" height="400" title="lidar_error">  <img src="https://user-images.githubusercontent.com/32844187/40505088-2f858692-5f61-11e8-9b19-47187f967a3d.png" width="350" height="400" title="ak16_abnormal">

What could cause the URG driver to send out this error? 

Thanks!

**Comment by anjinkristou** [comment]
I am interested to know more about this issue. Do you have a pattern to reproduce this issue?

**Comment by reinzor** [comment]
We had contact with `Hokuyo` and the reason for this is that this status is only fetched once (when the scanner was not initialized properly by the safety system).
