### ISSUE TITLE
Melodic release please!

### ISSUE THREAD

**Issue by boilerbots** [ros-drivers/urg_node#45]
Sure would be nice to keep up with the ROS releases. Melodic is the stable long term release now.

**Comment by doisyg** [comment]
Agreed!

**Comment by tonybaltovski** [comment]
@boilerbots @doisyg Blocked on releasing `urg_c` for melodic and some maintainer updates (https://github.com/ros/rosdistro/pull/18540)

**Comment by boilerbots** [comment]
The urg_node and urg_c build for me under Ubuntu 18.04 and Melodic. I hope to test it tomorrow with hardware, works in simulation. 

Curt

**Comment by tonybaltovski** [comment]
`urg_c` has been released but still waiting on ros-perception/laser_proc#4.

**Comment by tonybaltovski** [comment]
Released ros/rosdistro#18870.
