### ISSUE TITLE
err when run urg_node

### ISSUE THREAD

**Issue by neeba** [ros-drivers/urg_node#5]
hi
i connect laser scanner 04lx  and type rosrun urg_node urg_node but this error occured
"terminate called after throwing an instance of 'std::length_error' what(): vector::_M_fill_insert Aborted (core dumped)" 
what can i do?

**Comment by chadrockey** [comment]
Please provide a list of your current parameters, as well as the specific device and firmware version for your Hokuyo.

Additionally, please check permissions on /dev/ttyACM0 by running 'sudo chmod 777 /dev/ttyACM0'.

It's also possible your laser is communicating using SCIP 1.0, please try updating the firmware on your laser to the latest version.  See more information here:
http://ros-users.122217.n3.nabble.com/hokuyo-node-error-td921464.html

**Comment by chadrockey** [comment]
This is an issue when an SCIP 1.0 laser is connected.  Updating the firmware resolved the issue.

It may be possible to print a helpful warning to users instead of the above failure.

**Comment by neeba** [comment]
How can i update my scip?

**Comment by chadrockey** [comment]
Try here:

http://www.hokuyo-aut.jp/02sensor/07scanner/download/u_dl_firmware.html

And is this not your teams ros answers question?http://answers.ros.org/question/78496/err-when-run-urg_node/

**Comment by neeba** [comment]
no is not my team's question
i have 2 laser scanner the first one updated correctly and worked properly but the second one in sensor details has err the err is 'no rom [20->20]" what should i do?

**Comment by chadrockey** [comment]
@neeba, did you find a solution?

**Comment by neeba** [comment]
no,I didn't find a solution...
do you have any solution?
