### ISSUE TITLE
How do call "UrgNode::run()" in latest code on ros2-devel branch

### ISSUE THREAD

**Issue by n-hamaike-esol** [ros-drivers/urg_node#66]
I'm trying to test "LaserScan Visualization" following this link(https://index.ros.org/p/urg_node/#dashing), but it doesn't work. (use UTM-30LX-EW)
The result of debugging, "UrgNode::run()" is not called.(I set break point by GDB but not stopped, and not called from anywhere in source code)

With refering to commit log, I guess it seems disappeared when "urg_node" modified to component node.
(https://github.com/ros-drivers/urg_node/pull/50/commits/ad15f2354307df77c4098c71f26ce361b9b10572)

I added "UrgNode::run()" caller, then it works.

In latest code on ros2-devel branch, How do call "UrgNode::run()"?
"UrgNode::run()" caller is not necessary?

I'd appreciate it if someone could answer my questions.

**Comment by mikeferguson** [comment]
So, here's the hack I added, seems to work (not sure if it breaks other compositions though): https://github.com/mikeferguson/urg_node/commit/f308eee4f6a567a01077f205db9d130124f564e0

**Comment by n-hamaike-esol** [comment]
@mikeferguson
thanks for your comments and fixes!

**Comment by mikeferguson** [comment]
Merged the proper fix - will do a release shortly
