### ISSUE TITLE
ROS2 Maintainer?

### ISSUE THREAD

**Issue by mikeferguson** [ros-drivers/urg_node#72]
I notice @tonybaltovski is still listed as maintainer for ROS2 package.xml, but hasn't really been involved in the ROS2 side of things. @clalancette has recently done the last release - are you planning to maintain this going forward or are you looking for a maintainer? I'm happy to be a maintainer of this package in ROS2 (debs/master are currently broken - I've opened PRs to fix that).

All I really would need is a thumbs up - I've already got permissions on ros-drivers since I maintain a few other repos here.

**Comment by clalancette** [comment]
@mikeferguson I don't have time to maintain the ros2 urg stuff going forwards, so I would love to have you as the maintainer.  As long as @tonybaltovski is fine with it, that would be great by me.

**Comment by tonybaltovski** [comment]
I am totally fine with that!  I could help as I use ROS2 more.

**Comment by clalancette** [comment]
@mikeferguson I'll suggest that you open a PR targeting `ros2-devel` to switch the package.xml maintainer tag to yourself.

One other thing: if you are willing to maintain urg_node for ROS 2, maybe you'd also consider maintaining https://github.com/ros-drivers/urg_c.git for the `ros2-devel` branch?

**Comment by mikeferguson** [comment]
Yeah, I can take both of these packages -- I'll open a PR on both repos to update package.xml

**Comment by clalancette** [comment]
> Yeah, I can take both of these packages -- I'll open a PR on both repos to update package.xml

Thanks!

**Comment by mikeferguson** [comment]
@clalancette - I already have permissions on the repos in ros-drivers - but can you get me access to the ros2-gbp? I was just starting to push a release of urg_c to foxy and realized I don't have permissions to the ros2-gbp repo.

**Comment by clalancette** [comment]
> @clalancette - I already have permissions on the repos in ros-drivers - but can you get me access to the ros2-gbp? I was just starting to push a release of urg_c to foxy and realized I don't have permissions to the ros2-gbp repo.

I've given you write access to both https://github.com/ros2-gbp/urg_node-release and https://github.com/ros2-gbp/urg_c-release .  Let me know if it doesn't work for you.

**Comment by mikeferguson** [comment]
Looks to be working - just released urg_c to foxy: https://github.com/ros/rosdistro/pull/25401

**Comment by mikeferguson** [comment]
@clalancette  - realized there is one more - urg_node_msgs-release (I'll also add myself as a maintainer there)

**Comment by clalancette** [comment]
Done now.

**Comment by mikeferguson** [comment]
Thanks -- looks like all repos are working.
