### ISSUE TITLE
How to disable interpolation for the sensor data (ros2-devel branch)

### ISSUE THREAD

**Issue by JaehyunShim** [ros-drivers/urg_node#82]
Hi, @mikeferguson 

As the title says, how can I disable interpolation for the sensor data? Also, if possible, can you add a parameter for setting the on/off state of interpolation for those users who need raw sensor data?

Jaehyun

**Comment by mikeferguson** [comment]
I'm not aware that this driver does any interpolation - can you post some screenshots or data that shows what interpolation you're seeing?

**Comment by JaehyunShim** [comment]
@mikeferguson 

In the picture below, you can see these noise data (red circles) presumably created by interpolation around the obstacles (blue circles). 
![Screenshot from 2020-12-22 09-58-09](https://user-images.githubusercontent.com/38637417/102836372-91379e80-443c-11eb-8d95-d76e82025188.png)

You can see these dots connecting the obstacles (blue circles) more clearly in the next picture. 
![Screenshot from 2020-12-22 10-00-36](https://user-images.githubusercontent.com/38637417/102836524-f12e4500-443c-11eb-9d6f-227202bfc67b.png)

**Comment by JaehyunShim** [comment]
FYI, UAM-05LP-T301 is what I am testing with.

**Comment by mikeferguson** [comment]
These are not "interpolation" - this is what is known (at least in ROS-land) as a "shadow" - and it's an artifact of the laser operation - not something the drivers do.

The ROS1 package "laser_filters" includes a shadow filter to remove these points (as was popularized on the PR2). The package is semi-ported to ROS2, I had previously tried to run it (about 3 months ago) but ran into issues at the time.

**Comment by mikeferguson** [comment]
Closing due to lack of response - please reopen if you find additional information that shows these are not sensor artifacts.
