### ISSUE TITLE
getID is not created

### ISSUE THREAD

**Issue by jeff-o** [ros-drivers/urg_node#9]
I've installed the urg_node package using apt-get and manually, and in either case it seems as though getID.cpp is not compiled into an executable.  I am running ROS Hydro in Ubuntu 12.04LTS.

Thanks!

**Comment by chadrockey** [comment]
Thanks, looks like we missed the install rule.  It will be a while until this goes through the buildfarm and gets pushed out.

In the meantime, I'd recommend using the almost identical code in getID in hokuyo_node.  Or building in a source overlay if you need getID for Ethernet.

**Comment by jeff-o** [comment]
Thanks for the quick reply! And yes, I've been using the getID from hokuyo_node so far.

**Comment by kmhallen** [comment]
The hokuyo_node package is not available in Kinetic. Any chance we can merge the simple fix?
